[2023-01-17T23:07:59.141+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: oetker.task_start scheduled__2023-01-16T23:07:37.134271+00:00 [queued]>
[2023-01-17T23:07:59.204+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: oetker.task_start scheduled__2023-01-16T23:07:37.134271+00:00 [queued]>
[2023-01-17T23:07:59.210+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T23:07:59.212+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-17T23:07:59.214+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T23:07:59.319+0000] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): task_start> on 2023-01-16 23:07:37.134271+00:00
[2023-01-17T23:07:59.335+0000] {taskinstance.py:1081} INFO - Dependencies not met for <TaskInstance: oetker.task_start scheduled__2023-01-16T23:07:37.134271+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-01-17T23:07:59.348+0000] {taskinstance.py:1081} INFO - Dependencies not met for <TaskInstance: oetker.task_start scheduled__2023-01-16T23:07:37.134271+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-01-17T23:07:59.349+0000] {standard_task_runner.py:55} INFO - Started process 496 to run task
[2023-01-17T23:07:59.384+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'oetker', 'task_start', 'scheduled__2023-01-16T23:07:37.134271+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/oetker/oetker.py', '--cfg-path', '/tmp/tmp0ajhr0hg']
[2023-01-17T23:07:59.392+0000] {standard_task_runner.py:83} INFO - Job 72: Subtask task_start
[2023-01-17T23:07:59.455+0000] {local_task_job.py:98} INFO - Task is not able to be run
[2023-01-17T23:07:59.841+0000] {task_command.py:389} INFO - Running <TaskInstance: oetker.task_start scheduled__2023-01-16T23:07:37.134271+00:00 [running]> on host 876fdb6abbd4
[2023-01-17T23:08:00.213+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=oetker
AIRFLOW_CTX_TASK_ID=task_start
AIRFLOW_CTX_EXECUTION_DATE=2023-01-16T23:07:37.134271+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-16T23:07:37.134271+00:00
[2023-01-17T23:08:00.223+0000] {python.py:177} INFO - Done. Returned value was: [Task_start]
[2023-01-17T23:08:00.336+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=oetker, task_id=task_start, execution_date=20230116T230737, start_date=20230117T230759, end_date=20230117T230800
[2023-01-17T23:08:00.609+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-17T23:08:00.716+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
